// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Temperature struct {
	ID          interface{} `json:"id"`
	Temperature float64     `json:"temperature"`
	CreatedAt   time.Time   `json:"createdAt"`
}
