// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
)

const createTableIfNotExistsTemperature = `-- name: CreateTableIfNotExistsTemperature :exec
CREATE TABLE IF NOT EXISTS temperatures (
  id SERIAL PRIMARY KEY,
  temperature REAL NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateTableIfNotExistsTemperature(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTableIfNotExistsTemperature)
	return err
}

const createTemperature = `-- name: CreateTemperature :one
INSERT INTO temperatures (
  temperature
) VALUES (
  ?
)
RETURNING id, temperature, created_at
`

func (q *Queries) CreateTemperature(ctx context.Context, temperature float64) (Temperature, error) {
	row := q.db.QueryRowContext(ctx, createTemperature, temperature)
	var i Temperature
	err := row.Scan(&i.ID, &i.Temperature, &i.CreatedAt)
	return i, err
}
